Peter/basic api functions
blackout1471/trust-us-school pull request #3
Opened 2022-11-21 07:23 UTC by Ripiter

2022-11-21 08:09 UTC, blackout1471 reviewed
All async methods should also be called async at the end

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Controllers/UserController.cs
> +        public async Task<ActionResult<UserToken>> Login(UserLogin userLogin)
Comment

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Controllers/UserCreateController.cs
> +        public async Task<ActionResult<UserToken>> Register(UserCreate userCreate)
Comment

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Helpers/Security.cs
> +        private static string GetEncryptedPassword(string password)
Fake it till you make it

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Managers/TokenManager.cs
> +        public UserToken GetUserTokenFromToken(string token)
<inheritDoc />

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Managers/TokenManager.cs
> +        public UserToken GetUserTokenFromToken(string token)
inheritdoc

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Managers/UserManager.cs
> +        public async Task<User> CreateUser(UserCreate userCreate)
inheritdoc

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Managers/UserManager.cs
> +            // checjs uf yser exuts
yes

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Models/UserLocation.cs
> +    public class UserLocation
D afuckieralksd

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApi/Providers/UserProvider.cs
> +        public async Task<DbUser> CreateUser(DbUser userCreate)
inheritdoc

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApiTest/Managers/UserManagerTest.cs
> +        {
// arrange, act, assert

2022-11-21 08:09 UTC, blackout1471 commented on Source/IdentityApi/IdentityApiTest/Managers/UserManagerTest.cs
> +        public void User_Should_ThrowOnLogin()
Refactor names WhatToExpect_When_ActionOccurs ex: ThrowException_When_UserLogin

2022-11-21 18:41 UTC, Geefy requested changes

2022-11-21 18:41 UTC, Geefy commented on Docs/ClassDiagrams/ApiClassDiagram.plantuml
> +    +GetuserByIdAsync(id : int) : Task<DbUser>
GetuserByIdAsync -> GetUserByIdAsync

2022-11-21 18:41 UTC, Geefy commented on Docs/SDDiagrams/CreateUserSD.plantuml
> +Security->User: Return salt
Should point back to UserManager and not User

2022-11-22 08:00 UTC, blackout1471 approved these changes

2022-11-22 08:02 UTC, Geefy approved these changes

2022-11-22 08:03 UTC, merged